### ISSUE TITLE
Bug: Doesn't play files in v0.8.6

### ISSUE THREAD

**Issue by Sravdar** [BlitzKraig/fvtt-VoiceActor#8] opened 2021-06-07 16:20 UTC
Knowing it says v0.8.5 compatible tried in FoundryVTT v0.8.6, DnD5e v1.3.3.

It records voice and saves it. Checked to be sure it has audio, it does. When you press "play" button on character sheet it doesn't play the audio. Tested the module by itself only, still same result.

Here's my discord in case its working on your side. Sravdar#8410

**Comment by Sravdar** [comment] 2021-06-07 16:24
Update: Also after recording it seems to break the world. And windows is struggling to delete ogg files.

**Comment by BlitzKraig** [comment] 2021-06-07 16:27
Hi Sravdar.

How are you hosting Foundry? Are you using SSL? What do you mean by "break the world"? Are you able to playback the ogg files outside of Foundry and hear the recording?

Thanks

**Comment by Sravdar** [comment] 2021-06-07 16:34
I'm self hosting foundry with windows app. Don't know what is SSL so i assume no.
I opened the .ogg file and yes it records. In odd way "grove music" show the voice length something like this (https://prnt.sc/14jynz8) (VLC just refuse to open it).

By break world i mean it doesn't load the map, any buttons doesn't work (including return to setup etc). It might be something else causing this, didn't tested too much about it.

**Comment by BlitzKraig** [comment] 2021-06-07 17:10
Hi Sravdar,
I'm looking into this, it seems my recording method misses out some metadata, I'm also seeing inability to play on VLC.
Will check into this further.

As far as I can tell, this shouldn't affect your world, that sounds like it may be something else.

**Comment by BlitzKraig** [comment] 2021-06-07 17:33
I have pulled the module from the browser for now until I can fix this issue, as I'm not comfortable saving files to the users machine that are essentially corrupt, and difficult to remove.

I am able to remove the files, but it takes a long time while Windows tries to work out what's going on.

Thanks for the feedback, I'll get this sorted and re-list the module.

**Comment by BlitzKraig** [comment] 2021-06-07 19:01
@Sravdar , just a quick update on getting rid of the corrupt ogg files.

It seems the best way to delete them is to select them all in Explorer and press Delete. Windows will act like it's not doing anything.
Wait a few seconds, then either restart your pc or sign out then back in. The files should be gone.

**Comment by amcvfx** [comment] 2021-06-09 20:15
I can confirm that there is no file playback in 0.8.6. This is for files that were created before upgrading to 0.8.6. I get this error when hitting play:

![image](https://user-images.githubusercontent.com/35099081/121423009-b9be4100-c967-11eb-8849-935ca3478cc5.png)

**Comment by BlitzKraig** [comment] 2021-06-09 20:54
Thanks for the extra feedback, that's very helpful. `Howl` should be gone, I'll need to check my code.

I'll be taking a look at this soon. I'll fix up playback, and also work out how to fix the "corrupt" files.

**Comment by DiceAndEasy** [comment] 2021-06-26 12:36
Hey! Confirming that clip playback does not work in 0.8.8 either. Recording seems to be working fine though (I checked my existing files and just recorded a new one, and they are all fine).

**Comment by DiceAndEasy** [comment] 2021-07-28 14:56
@BlitzKraig any idea when we can expect a fix for the playback issue?

**Comment by BlitzKraig** [comment] 2021-07-28 16:19
Hi @funwithfondue ,
I've been away from development for a few weeks due to job stuff.
I expect to return soon, though don't have a date for this issue. Fixing and re-releasing VoiceActor is high on the priority list though.

Thanks

**Comment by DiceAndEasy** [comment] 2021-07-28 18:35
Thanks a lot for the update!

**Comment by BlitzKraig** [comment] 2021-08-09 15:17
Hi @funwithfondue , please try the latest version out, and let me know if it has fixed your issue.

Thanks

**Comment by DiceAndEasy** [comment] 2021-08-09 17:33
Thanks for the patch @BlitzKraig! With the new patch it seems like all my actors have been disconnected from their sound files. Is there a way for me to relink the sound files to the actors without having to rerecord the sound files?

Recording a new sound file works and playback works now!

**Comment by BlitzKraig** [comment] 2021-08-09 17:57
Unfortunately, there is no easy way to relink them. If you are able to, you can maybe rename all of your existing files with ".wav" instead of ".ogg", but I can't say for sure whether that will work.

**Comment by DiceAndEasy** [comment] 2021-08-09 20:37
That fixed it! All of the old sound files work now that I changed the extension from .ogg to .wav! Thanks a lot!

**Comment by BlitzKraig** [comment] 2021-08-09 21:39
Great stuff! Closing, enjoy!

**Closed as completed by BlitzKraig** 2021-08-09 21:39 UTC
